#!/usr/bin/env node

/**
 * Phase 06 Tier 4 Adapter Tests
 *
 * Tests for Trae and Qoder best-effort adapters.
 * Covers:
 * - Registry discovery (14 adapters)
 * - Trae: .trae/rules/ markdown, references, best-effort header, install/uninstall
 * - Qoder: .qoder/rules/ markdown, inlined metrics, Agent/Quest mode hints, install/uninstall
 * - bestEffort capability flag and CLI display
 *
 * Run with: node --test tests/phase-06-tier4-adapters.test.js
 */

const test = require("node:test");
const assert = require("node:assert");
const path = require("path");
const fs = require("fs");
const os = require("os");

// === Imports ===
const TraeAdapter = require("../adapters/trae");
const QoderAdapter = require("../adapters/qoder");

const PKG_DIR = path.resolve(__dirname, "..");

// === Helpers ===

function createTempDir(prefix = "test-") {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  return {
    dir,
    cleanup: () => {
      if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    },
  };
}

// === Registry Discovery ===

test("Registry: discovers all 14 adapters", () => {
  delete require.cache[require.resolve("../adapters/registry")];
  const registry = require("../adapters/registry");
  const list = registry.list();
  const names = list.map((a) => a.name);
  assert.ok(names.includes("trae"), "should have trae");
  assert.ok(names.includes("qoder"), "should have qoder");
  assert.strictEqual(list.length, 14, "should have exactly 14 adapters");
});

// === Trae Adapter ===

test("Trae: name and displayName", () => {
  const adapter = new TraeAdapter();
  assert.strictEqual(adapter.name, "trae");
  assert.strictEqual(adapter.displayName, "Trae");
});

test("Trae: has bestEffort capability flag", () => {
  const adapter = new TraeAdapter();
  assert.strictEqual(adapter.capabilities.bestEffort, true);
});

test("Trae: rejects global scope", () => {
  const adapter = new TraeAdapter();
  const result = adapter.install({ packageDir: PKG_DIR, scope: "global", projectRoot: "/tmp", dryRun: true });
  assert.strictEqual(result.success, false);
  assert.ok(result.message.includes("global"));
});

test("Trae: dry-run lists rules and references", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-dry-");
  try {
    const result = adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir, dryRun: true });
    assert.strictEqual(result.success, true);
    assert.ok(result.files.some((f) => f.includes("refactoring-skill.md")), "should list skill rule");
    assert.ok(result.files.some((f) => f.includes("refactoring-references")), "should list references");
    assert.ok(result.message.includes("best-effort"), "dry-run message should mention best-effort");
  } finally {
    temp.cleanup();
  }
});

test("Trae: install creates rules with best-effort header", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-install-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });

    const skillPath = path.join(temp.dir, ".trae", "rules", "refactoring-skill.md");
    assert.ok(fs.existsSync(skillPath), "should create skill rule");
    const content = fs.readFileSync(skillPath, "utf-8");
    assert.ok(content.includes("Generated by refactoring-kit"), "should have best-effort header");
    assert.ok(!content.includes("$ARGUMENTS"), "should not have $ARGUMENTS");
    assert.ok(!content.includes("Activate `refactoring`"), "should not have Activate directive");
  } finally {
    temp.cleanup();
  }
});

test("Trae: install creates command rules", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-cmds-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });

    const rulesDir = path.join(temp.dir, ".trae", "rules");
    assert.ok(fs.existsSync(path.join(rulesDir, "refactoring-review.md")), "should create review rule");
    assert.ok(fs.existsSync(path.join(rulesDir, "refactoring-fast.md")), "should create fast rule");
    assert.ok(fs.existsSync(path.join(rulesDir, "refactoring-plan.md")), "should create plan rule");
  } finally {
    temp.cleanup();
  }
});

test("Trae: install copies reference files", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-refs-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });
    const refsDir = path.join(temp.dir, ".trae", "rules", "refactoring-references");
    assert.ok(fs.existsSync(refsDir), "should create references dir");
    assert.ok(fs.existsSync(path.join(refsDir, "code-smells.md")), "should copy code-smells.md");
  } finally {
    temp.cleanup();
  }
});

test("Trae: uninstall removes rules and references", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-uninstall-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });
    adapter.uninstall({ scope: "project", projectRoot: temp.dir });

    const rulesDir = path.join(temp.dir, ".trae", "rules");
    assert.ok(!fs.existsSync(path.join(rulesDir, "refactoring-skill.md")), "should remove skill rule");
    assert.ok(!fs.existsSync(path.join(rulesDir, "refactoring-references")), "should remove references");
    assert.ok(!adapter.hasMarker(path.join(temp.dir, ".trae")), "should remove marker");
  } finally {
    temp.cleanup();
  }
});

test("Trae: uninstall is no-op if not installed", () => {
  const adapter = new TraeAdapter();
  const temp = createTempDir("trae-noop-");
  try {
    const result = adapter.uninstall({ scope: "project", projectRoot: temp.dir });
    assert.ok(result.success);
    assert.ok(result.message.includes("nothing to remove"));
  } finally {
    temp.cleanup();
  }
});

// === Qoder Adapter ===

test("Qoder: name and displayName", () => {
  const adapter = new QoderAdapter();
  assert.strictEqual(adapter.name, "qoder");
  assert.strictEqual(adapter.displayName, "Qoder");
});

test("Qoder: has bestEffort capability flag", () => {
  const adapter = new QoderAdapter();
  assert.strictEqual(adapter.capabilities.bestEffort, true);
});

test("Qoder: rejects global scope", () => {
  const adapter = new QoderAdapter();
  const result = adapter.install({ packageDir: PKG_DIR, scope: "global", projectRoot: "/tmp", dryRun: true });
  assert.strictEqual(result.success, false);
  assert.ok(result.message.includes("global"));
});

test("Qoder: dry-run lists rules", () => {
  const adapter = new QoderAdapter();
  const temp = createTempDir("qoder-dry-");
  try {
    const result = adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir, dryRun: true });
    assert.strictEqual(result.success, true);
    assert.ok(result.files.some((f) => f.includes("refactoring-skill.md")), "should list skill rule");
    assert.ok(result.message.includes("best-effort"), "dry-run message should mention best-effort");
  } finally {
    temp.cleanup();
  }
});

test("Qoder: install creates skill rule with inlined metrics", () => {
  const adapter = new QoderAdapter();
  const temp = createTempDir("qoder-install-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });

    const skillPath = path.join(temp.dir, ".qoder", "rules", "refactoring-skill.md");
    assert.ok(fs.existsSync(skillPath), "should create skill rule");
    const content = fs.readFileSync(skillPath, "utf-8");
    assert.ok(content.includes("Generated by refactoring-kit"), "should have best-effort header");
    assert.ok(content.includes("Inlined Reference: Key Metrics"), "should have inlined metrics");
    assert.ok(content.includes("Cyclomatic complexity"), "should include complexity threshold");
    assert.ok(content.includes("Priority order"), "should include priority order");
  } finally {
    temp.cleanup();
  }
});

test("Qoder: command rules include Agent/Quest mode hints", () => {
  const adapter = new QoderAdapter();
  const temp = createTempDir("qoder-modes-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });

    const rulesDir = path.join(temp.dir, ".qoder", "rules");

    // Review should suggest Agent Mode
    const reviewContent = fs.readFileSync(path.join(rulesDir, "refactoring-review.md"), "utf-8");
    assert.ok(reviewContent.includes("Agent Mode"), "review should suggest Agent Mode");

    // Plan should suggest Quest Mode
    const planContent = fs.readFileSync(path.join(rulesDir, "refactoring-plan.md"), "utf-8");
    assert.ok(planContent.includes("Quest Mode"), "plan should suggest Quest Mode");
  } finally {
    temp.cleanup();
  }
});

test("Qoder: command rules have no Claude-specific syntax", () => {
  const adapter = new QoderAdapter();
  const temp = createTempDir("qoder-clean-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });
    const rulesDir = path.join(temp.dir, ".qoder", "rules");
    for (const file of fs.readdirSync(rulesDir)) {
      const content = fs.readFileSync(path.join(rulesDir, file), "utf-8");
      assert.ok(!content.includes("$ARGUMENTS"), `${file} should not have $ARGUMENTS`);
      assert.ok(!content.includes("Activate `refactoring`"), `${file} should not have Activate directive`);
    }
  } finally {
    temp.cleanup();
  }
});

test("Qoder: uninstall removes rules", () => {
  const adapter = new QoderAdapter();
  const temp = createTempDir("qoder-uninstall-");
  try {
    adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });
    adapter.uninstall({ scope: "project", projectRoot: temp.dir });

    const rulesDir = path.join(temp.dir, ".qoder", "rules");
    const remaining = fs.existsSync(rulesDir)
      ? fs.readdirSync(rulesDir).filter((f) => f.includes("refactoring"))
      : [];
    assert.strictEqual(remaining.length, 0, "should remove all rule files");
    assert.ok(!adapter.hasMarker(path.join(temp.dir, ".qoder")), "should remove marker");
  } finally {
    temp.cleanup();
  }
});

// === CLI Integration ===

test("CLI: tools command shows all 14 adapters with best-effort labels", () => {
  const { execFileSync } = require("child_process");
  const cliPath = path.resolve(__dirname, "..", "cli.js");
  const output = execFileSync(process.execPath, [cliPath, "tools"], { encoding: "utf-8" });
  assert.ok(output.includes("trae"), "should list trae");
  assert.ok(output.includes("qoder"), "should list qoder");
  assert.ok(output.includes("Supported tools (14)"), "should show count 14");
  assert.ok(output.includes("best effort"), "should show best effort label");
});

// === Install/Uninstall Cycle ===

test("Full cycle: install then uninstall for both Tier 4 adapters", () => {
  const adapters = [new TraeAdapter(), new QoderAdapter()];

  for (const adapter of adapters) {
    const temp = createTempDir(`cycle-${adapter.name}-`);
    try {
      const installResult = adapter.install({ packageDir: PKG_DIR, scope: "project", projectRoot: temp.dir });
      assert.ok(installResult.success, `${adapter.name}: install should succeed`);
      assert.ok(installResult.files.length > 0, `${adapter.name}: should list installed files`);

      const uninstallResult = adapter.uninstall({ scope: "project", projectRoot: temp.dir });
      assert.ok(uninstallResult.success, `${adapter.name}: uninstall should succeed`);
    } finally {
      temp.cleanup();
    }
  }
});
